import type { AnyCommand } from './command.js';
import { CliError } from './errors.js';
import { renderAgentBlock } from './init/block.js';
import { CLI_NAME } from './meta.js';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

type Env = Record<string, string | undefined>;

export const SKILL_NAME = CLI_NAME;
/** The copy of `.claude/skills/bai-agent` the package ships (see scripts/copy-skill.mjs). */
export const SHIPPED_SKILL_DIR = 'skill';
/** The standalone agent block, written next to the cookbook on install. */
export const AGENT_BLOCK_FILE = 'references/agent-block.md';

/**
 * The skill source: the package's shipped copy, or — when running from a
 * checkout's `src/` or `dist/` before a build copied it — the repo's own
 * `.claude/skills/bai-agent`. Walks up from this module like the mappings do.
 */
export function shippedSkillDir(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let depth = 0; depth < 6; depth += 1) {
    // The checkout's source first: a stale `skill/` from an earlier build
    // must not win over an edited SKILL.md while developing.
    for (const candidate of [
      join(dir, '.claude', 'skills', SKILL_NAME),
      join(dir, SHIPPED_SKILL_DIR),
    ]) {
      if (existsSync(join(candidate, 'SKILL.md'))) return candidate;
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new CliError(
    'internal',
    `Cannot locate the ${SKILL_NAME} skill shipped with this CLI.`,
    { hint: 'pnpm --filter backend.ai-agent-cli build' },
  );
}

/** `~/.claude/skills` — or under `$CLAUDE_CONFIG_DIR`, which Claude Code honours. */
export function claudeSkillsDir(env: Env = process.env): string {
  const base = env.CLAUDE_CONFIG_DIR?.trim() || join(homedir(), '.claude');
  return join(base, 'skills');
}

export function installedSkillDir(env: Env = process.env): string {
  return join(claudeSkillsDir(env), SKILL_NAME);
}

function walk(root: string, dir = root): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(root, path));
    else files.push(relative(root, path).split(sep).join('/'));
  }
  return files.sort();
}

/** `~`-relative when under the home directory, as a human would write it. */
export function displayPath(path: string): string {
  const home = homedir();
  return path.startsWith(home + sep) ? `~${path.slice(home.length)}` : path;
}

export type SkillInstallOutcome = 'installed' | 'updated' | 'unchanged';

export interface SkillInstallData {
  path: string;
  source: string;
  outcome: SkillInstallOutcome;
  files: string[];
}

export interface SkillInstallOptions {
  commands: AnyCommand[];
  env?: Env;
  /** Override the destination (tests). */
  targetDir?: string;
  sourceDir?: string;
}

/**
 * Copy the skill into Claude Code's user skills directory and generate the
 * standalone agent block beside it, so a machine without the WebUI checkout —
 * and therefore without its CLAUDE.md — still carries the workflow contract.
 */
export function installSkill(options: SkillInstallOptions): SkillInstallData {
  const env = options.env ?? process.env;
  const source = options.sourceDir ?? shippedSkillDir();
  const target = options.targetDir ?? installedSkillDir(env);
  const existed = existsSync(join(target, 'SKILL.md'));

  const writes = new Map<string, string>();
  for (const file of walk(source)) {
    writes.set(file, readFileSync(join(source, file), 'utf8'));
  }
  writes.set(
    AGENT_BLOCK_FILE,
    [
      `# ${CLI_NAME} agent block (standalone)`,
      '',
      `Generated by \`${CLI_NAME} init\` from the installed CLI's command registry — the`,
      'same block a WebUI checkout carries in its CLAUDE.md, worded for a machine that',
      `has only the npm package and a synced data checkout. Re-run \`${CLI_NAME} init\``,
      'after upgrading the CLI.',
      '',
      renderAgentBlock(options.commands, {
        mode: 'standalone',
        skillPath: displayPath(join(target, 'SKILL.md')),
      }),
      '',
    ].join('\n'),
  );

  let changed = false;
  for (const [file, content] of writes) {
    const path = join(target, file);
    const current =
      existsSync(path) && statSync(path).isFile()
        ? readFileSync(path, 'utf8')
        : undefined;
    if (current === content) continue;
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, 'utf8');
    changed = true;
  }

  return {
    path: target,
    source,
    outcome: !existed ? 'installed' : changed ? 'updated' : 'unchanged',
    files: [...writes.keys()].sort(),
  };
}
