import type { AnyCommand } from './command.js';
import { CliError } from './errors.js';
import { renderAgentBlock } from './init/block.js';
import { CLI_NAME } from './meta.js';
import { displayPath, installedSkillDir } from './skill-path.js';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

type Env = Record<string, string | undefined>;

export const SKILL_NAME = CLI_NAME;
/** The skill's home: `packages/backend.ai-agent-cli/skill`, shipped as-is in the tarball. */
export const SHIPPED_SKILL_DIR = 'skill';
/** The standalone agent block, written next to the cookbook on install. */
export const AGENT_BLOCK_FILE = 'references/agent-block.md';

/**
 * The package's own `skill/` directory. Walking up from this module works
 * from `src/` and from the bundled `dist/` alike, as the mappings loader does.
 */
export function shippedSkillDir(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let depth = 0; depth < 6; depth += 1) {
    const candidate = join(dir, SHIPPED_SKILL_DIR);
    if (existsSync(join(candidate, 'SKILL.md'))) return candidate;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new CliError(
    'internal',
    `Cannot locate the ${SKILL_NAME} skill shipped with this CLI.`,
    { hint: 'pnpm --filter backend.ai-agent-cli build' },
  );
}

export {
  claudeSkillsDir,
  displayPath,
  installedSkillDir,
  installedSkillPath,
} from './skill-path.js';

function walk(root: string, dir = root): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(root, path));
    else files.push(relative(root, path).split(sep).join('/'));
  }
  return files.sort();
}

export type SkillInstallOutcome = 'installed' | 'updated' | 'unchanged';

export interface SkillInstallData {
  path: string;
  source: string;
  outcome: SkillInstallOutcome;
  files: string[];
  /** Files from an older install that this CLI no longer ships. */
  removed?: string[];
}

export interface SkillInstallOptions {
  commands: AnyCommand[];
  env?: Env;
  /** Override the destination (tests). */
  targetDir?: string;
  sourceDir?: string;
}

/**
 * Copy the skill into Claude Code's user skills directory and generate the
 * standalone agent block beside it, so a machine without the WebUI checkout —
 * and therefore without its CLAUDE.md — still carries the workflow contract.
 */
export function installSkill(options: SkillInstallOptions): SkillInstallData {
  const env = options.env ?? process.env;
  const source = options.sourceDir ?? shippedSkillDir();
  const target = options.targetDir ?? installedSkillDir(env);
  const existed = existsSync(join(target, 'SKILL.md'));

  const writes = new Map<string, string>();
  for (const file of walk(source)) {
    writes.set(file, readFileSync(join(source, file), 'utf8'));
  }
  writes.set(
    AGENT_BLOCK_FILE,
    [
      `# ${CLI_NAME} agent block (standalone)`,
      '',
      `Generated by \`${CLI_NAME} init\` from the installed CLI's command registry — the`,
      'same block a WebUI checkout carries in its CLAUDE.md, worded for a machine that',
      `has only the npm package and a synced data checkout. Re-run \`${CLI_NAME} init\``,
      'after upgrading the CLI.',
      '',
      renderAgentBlock(options.commands, {
        mode: 'standalone',
        skillPath: displayPath(join(target, 'SKILL.md')),
      }),
      '',
    ].join('\n'),
  );

  let changed = false;
  for (const [file, content] of writes) {
    const path = join(target, file);
    const current =
      existsSync(path) && statSync(path).isFile()
        ? readFileSync(path, 'utf8')
        : undefined;
    if (current === content) continue;
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, 'utf8');
    changed = true;
  }
  // The directory is package-owned: a file a newer CLI no longer ships is
  // stale instruction, not user data, and goes away with the reinstall.
  const removed: string[] = [];
  if (existed) {
    for (const file of walk(target)) {
      if (writes.has(file)) continue;
      rmSync(join(target, file), { force: true });
      removed.push(file);
      changed = true;
    }
  }

  return {
    path: target,
    source,
    outcome: !existed ? 'installed' : changed ? 'updated' : 'unchanged',
    files: [...writes.keys()].sort(),
    ...(removed.length > 0 ? { removed: removed.sort() } : {}),
  };
}
