import { default as ErrorList } from './ErrorList';
import { default as InternalForm, FormProvider, useForm } from './Form';
import { default as FormItem } from './FormItem';
import { default as List } from './List';
import { default as useWatch, useFormInstance } from './useWatch';
type InternalFormType = typeof InternalForm;
interface FormInterface extends InternalFormType {
    Item: typeof FormItem;
    List: typeof List;
    ErrorList: typeof ErrorList;
    useForm: typeof useForm;
    useFormInstance: typeof useFormInstance;
    useWatch: typeof useWatch;
    Provider: typeof FormProvider;
}
declare const Form: FormInterface;
export default Form;
export { Form };
export { FormItem, List as FormList, ErrorList, FormProvider, useForm, useWatch, useFormInstance, };
export { default as BAIFormItem } from './FormItem';
export { default as BAIFormItemVisual, type BAIFormItemVisualProps, } from './FormItemVisual';
export { FormItemInputContext, NoStyleItemContext, FormConfigContext, type FormConfig, type FormItemStatusContextValue, type RequiredMark, } from './context';
export { FormConfigProvider, useFormValidateMessages, } from './FormConfigProvider';
export { FormStore } from './FormStore';
export { defaultValidateMessages } from './messages';
export type { FormProps, FormRef } from './Form';
export type { FormItemProps } from './FormItem';
export type { ListProps as FormListProps, ListField, ListOperations, } from './List';
export type { ErrorListProps } from './ErrorList';
export type { WatchOptions } from './useWatch';
export type { FormInstance, FieldData, FieldError, Meta, NamePath, InternalNamePath, Rule, RuleObject, RuleRender, RuleType, ScrollOptions, Store, StoreValue, ValidateErrorEntity, ValidateMessages, ValidateOptions, ValidatorRule, } from './interface';
