packages:
  - react
  - packages/backend.ai-ui

ignoredBuiltDependencies:
  - "@vaadin/vaadin-usage-statistics"

onlyBuiltDependencies:
  - bufferutil
  - core-js
  - core-js-pure
  - electron
  - es5-ext
  - esbuild
  - unrs-resolver
  - utf-8-validate

patchedDependencies:
  "@cloudscape-design/board-components@3.0.60": react/patches/@cloudscape-design__board-components@3.0.60.patch
  rc-field-form@2.7.0: react/patches/rc-field-form.patch
  react-scripts@5.0.1: react/patches/react-scripts@5.0.1.patch

minimumReleaseAge: 1440

catalog:
  typescript: "^5.7.2"
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router-dom: ^6.30.0
  relay-compiler: "^20.1.0"
  graphql: "^16.10.0"
  react-relay: ^20.1.0
  relay-runtime: ^20.1.0
  antd: ^5.27.4
  antd-style: ^3.7.1
  "@ant-design/icons": ^6.0.0
  lucide-react: ^0.542.0
  dayjs: ^1.11.13
  lodash: ^4.17.21
  "@types/lodash": ^4.17.13
  "@types/react": ^19.0.7
  "@types/react-dom": "^19.0.3"
  "@types/react-relay": "^18.2.1"
  "@types/relay-runtime": "^19.0.2"
  "@types/relay-test-utils": "^19.0.0"
