packages:
  - react
  - packages/backend.ai-ui

ignoredBuiltDependencies:
  - "@vaadin/vaadin-usage-statistics"

onlyBuiltDependencies:
  - bufferutil
  - core-js
  - core-js-pure
  - electron
  - es5-ext
  - esbuild
  - unrs-resolver
  - utf-8-validate

patchedDependencies:
  "@cloudscape-design/board-components@3.0.60": react/patches/@cloudscape-design__board-components@3.0.60.patch
  rc-field-form@2.7.1: react/patches/rc-field-form.patch
  react-scripts@5.0.1: react/patches/react-scripts@5.0.1.patch
  ansi_up@6.0.6: react/patches/ansi_up@6.0.6.patch
  "@lobehub/fluent-emoji@2.0.0": react/patches/lobehub__fluent-emoji@2.0.0.patch

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - node-forge@1.3.2
  - react@19.2.1
  - react-dom@19.2.1