packages:
  - react
onlyBuiltDependencies:
  - bufferutil
  - core-js
  - core-js-pure
  - electron
  - es5-ext
  - esbuild
  - utf-8-validate
ignoredBuiltDependencies:
  - '@vaadin/vaadin-usage-statistics'
