/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/built/backendai-default.ts
 * Command: astryx theme build src/astryx-theme/built/backendai-default.ts --out src/astryx-theme/built/backendai-default-built.css
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

/// <reference path="./bai-r17-default-brand-h161l5oh.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const baiR17DefaultBrandH161l5ohTheme: DefinedTheme;
