/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/built/backendai-default.ts
 * Command: astryx theme build src/astryx-theme/built/backendai-default.ts --out src/astryx-theme/built/backendai-default-built.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./bai-r28-default-brand-hsutlj6.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const baiR28DefaultBrandHsutlj6Theme: DefinedTheme;
