/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/built/backendai-default.ts
 * Command: astryx theme build src/astryx-theme/built/backendai-default.ts --out src/astryx-theme/built/backendai-default-built.css
 * CLI: @astryxdesign/cli@0.4.7
 * Core: @astryxdesign/core@0.4.7
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Text' {
  interface TextColorMap {
    'danger': true;
    'warning': true;
    'success': true;
  }
}

declare module '@astryxdesign/core/Text' {
  interface TextColorMap {
    'danger': true;
    'warning': true;
    'success': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
