/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/built/backendai-default.ts
 * Command: astryx theme build src/astryx-theme/built/backendai-default.ts --out src/astryx-theme/built/backendai-default-built.css
 * CLI: @astryxdesign/cli@0.4.0
 * Core: @astryxdesign/core@0.4.0
 */

/// <reference path="./bai-r16-default-brand-h4glqj5.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const baiR16DefaultBrandH4glqj5Theme: DefinedTheme;
