/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/built/backendai-default.ts
 * Command: astryx theme build src/astryx-theme/built/backendai-default.ts --out src/astryx-theme/built/backendai-default-built.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

<<<<<<<< HEAD:react/src/astryx-theme/built/bai-r24-default-brand-h1you1vi.d.ts
/// <reference path="./bai-r24-default-brand-h1you1vi.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const baiR24DefaultBrandH1you1viTheme: DefinedTheme;
========
/// <reference path="./bai-r23-default-brand-hmvbsp8.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const baiR23DefaultBrandHmvbsp8Theme: DefinedTheme;
>>>>>>>> 42764c4e8 (feat(FR-3605): register the --bai-* custom token layer in the Astryx recipe (REV 23)):react/src/astryx-theme/built/bai-r23-default-brand-hmvbsp8.d.ts
