/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/built/backendai-default.ts
 * Command: astryx theme build src/astryx-theme/built/backendai-default.ts --out src/astryx-theme/built/backendai-default-built.css
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface HeadingTypeMap {
    'display-1': true;
    'display-2': true;
    'display-3': true;
  }
}

declare module '@astryxdesign/core/Text' {
  interface TextColorMap {
    'danger': true;
    'warning': true;
    'success': true;
  }
}

declare module '@astryxdesign/core/Text' {
  interface TextColorMap {
    'danger': true;
    'warning': true;
    'success': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}

declare module '@astryxdesign/core/Avatar' {
  interface AvatarStatusDotVariantMap {
    'success': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/Banner' {
  interface BannerStatusMap {
    'info': true;
    'error': true;
    'success': true;
    'warning': true;
  }
}
