/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/built/backendai-default.ts
 * Command: astryx theme build src/astryx-theme/built/backendai-default.ts --out src/astryx-theme/built/backendai-default-built.css
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

<<<<<<<< HEAD:react/src/astryx-theme/built/bai-r16-default-brand-h161l5oh.d.ts
/// <reference path="./bai-r16-default-brand-h161l5oh.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const baiR16DefaultBrandH161l5ohTheme: DefinedTheme;
========
/// <reference path="./bai-r16-default-brand-hu4alvq.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const baiR16DefaultBrandHu4alvqTheme: DefinedTheme;
>>>>>>>> c71d4ebf5 (fix(FR-3558): make palette row hover clearly visible in both themes):react/src/astryx-theme/built/bai-r16-default-brand-hu4alvq.d.ts
