/**
 @license
 Copyright (c) 2015-2026 Lablup Inc. All rights reserved.

 FROZEN REFERENCE — the real `@ant-design/colors` output, captured from a
 clean install of version 7.2.1 (pulling `@ant-design/fast-color` 2.0.6) at
 the moment that dev dependency was removed.

 `vendor/antdColors.ts` is a hand-port of that package, and its parity was
 originally asserted by diffing it against the live import — which is what
 kept `@ant-design/colors` in `devDependencies` long after nothing rendered
 with antd. The vendored file's own header always said the test "flips to
 fixed expected values" once the npm package is dropped. This is that flip,
 and it mirrors what `antdDesignTokenFixture.ts` already did for `antd`.

 The contract is unchanged: the vendored port is pinned to 7.2.1 by design,
 so freezing 7.2.1's output captures exactly the same contract the live
 import did. Upstream drift was never a signal this repo acted on.

 Generated by a script run outside the repo against the real package; not
 regenerable in-tree and not meant to be. If the vendored port stops matching
 these values, the port changed — investigate that, do not edit this table.
 */
/** Seeds these ramps were captured for — mirrors REPO_SEEDS in the test. */
export declare const ANTD_COLORS_REFERENCE_SEEDS: readonly ["#FF7A00", "#DC6B03", "#028DF2", "#009BDD", "#00BD9B", "#03A487", "#FF4D4F", "#DC4446", "#FAAD14", "#1677ff", "#666666", "#000000", "#ffffff"];
/** `generate(seed)` — light ramps. */
export declare const ANTD_COLORS_LIGHT_RAMPS: Record<string, string[]>;
/** `generate(seed, { theme: 'dark' })` — dark ramps on the default #141414. */
export declare const ANTD_COLORS_DARK_RAMPS: Record<string, string[]>;
/** `generate(seed, { theme: 'dark', backgroundColor: '#000' })`. */
export declare const ANTD_COLORS_DARK_ON_BLACK_RAMPS: Record<string, string[]>;
/** `presetPalettes` — the full upstream preset table. */
export declare const ANTD_COLORS_PRESET_PALETTES: Record<string, string[]>;
/** `presetDarkPalettes` — the full upstream dark preset table. */
export declare const ANTD_COLORS_PRESET_DARK_PALETTES: Record<string, string[]>;
