import {
  DeploymentLauncherFormValue,
  DeploymentLauncherStepKey,
} from '../pages/DeploymentLauncherPage';
import { Typography, Form, Descriptions, Tag } from 'antd';
import { BAICard, BAIFlex } from 'backend.ai-ui';
import _ from 'lodash';
import React from 'react';
import { useTranslation } from 'react-i18next';

const DeploymentLauncherPreview: React.FC<{
  onClickEditStep: (stepKey: DeploymentLauncherStepKey) => void;
}> = ({ onClickEditStep }) => {
  const { t } = useTranslation();
  const form = Form.useFormInstance<DeploymentLauncherFormValue>();

  return (
    <BAIFlex direction="column" gap="md">
      {/* Metadata and Network Summary */}
      <BAICard
        title={t('deployment.launcher.MetadataAndNetwork')}
        showDivider
        size="small"
        status={
          form.getFieldError(['metadata', 'name']).length > 0 ||
          form.getFieldError(['metadata', 'tags']).length > 0 ||
          form.getFieldError(['networkAccess', 'preferredDomainName']).length >
            0 ||
          form.getFieldError(['networkAccess', 'openToPublic']).length > 0
            ? 'error'
            : undefined
        }
        extraButtonTitle={t('button.Edit')}
        onClickExtraButton={() => onClickEditStep('metadata')}
      >
        <Descriptions size="small" column={1}>
          <Descriptions.Item label={t('deployment.launcher.DeploymentName')}>
            {form.getFieldValue(['metadata', 'name']) || (
              <Typography.Text type="secondary">
                {t('general.None')}
              </Typography.Text>
            )}
          </Descriptions.Item>
          {form.getFieldValue(['metadata', 'tags'])?.length > 0 && (
            <Descriptions.Item label={t('deployment.launcher.Tags')}>
              <BAIFlex direction="row" gap="xs" wrap="wrap">
                {form
                  .getFieldValue(['metadata', 'tags'])
                  .map((tag: string, index: number) => (
                    <Tag key={index}>{tag}</Tag>
                  ))}
              </BAIFlex>
            </Descriptions.Item>
          )}
          <Descriptions.Item
            label={t('deployment.launcher.PreferredDomainName')}
          >
            {form.getFieldValue(['networkAccess', 'preferredDomainName']) || (
              <Typography.Text type="secondary">
                {t('general.AutoGenerated')}
              </Typography.Text>
            )}
          </Descriptions.Item>
          <Descriptions.Item label={t('deployment.launcher.OpenToPublic')}>
            {form.getFieldValue(['networkAccess', 'openToPublic'])
              ? t('button.Yes')
              : t('button.No')}
          </Descriptions.Item>
        </Descriptions>
      </BAICard>

      {/* Resource and Cluster Configuration Summary */}
      <BAICard
        title={t('deployment.launcher.ResourceAllocation')}
        showDivider
        size="small"
        status={
          form.getFieldError('cluster_mode').length > 0 ||
          form.getFieldError('cluster_size').length > 0 ||
          form.getFieldError('resourceGroup').length > 0 ||
          _.some(form.getFieldValue('resource'), (v, key) => {
            return (
              // @ts-ignore
              form.getFieldError(['resource', key]).length > 0
            );
          })
            ? 'error'
            : undefined
        }
        extraButtonTitle={t('button.Edit')}
        onClickExtraButton={() => onClickEditStep('resources')}
      >
        <Descriptions size="small" column={1}>
          <Descriptions.Item label={t('deployment.launcher.ClusterMode')}>
            {form.getFieldValue('cluster_mode') === 'single-node'
              ? t('deployment.launcher.SingleNode')
              : t('deployment.launcher.MultiNode')}
          </Descriptions.Item>
          <Descriptions.Item label={t('deployment.launcher.ClusterSize')}>
            {form.getFieldValue('cluster_size') || 1}
          </Descriptions.Item>
          <Descriptions.Item label={t('deployment.launcher.ResourceGroup')}>
            {form.getFieldValue('resourceGroup') || (
              <Typography.Text type="secondary">
                {t('general.None')}
              </Typography.Text>
            )}
          </Descriptions.Item>
          <Descriptions.Item
            label={t('deployment.launcher.ResourceAllocation')}
          >
            <BAIFlex direction="row" gap="xs" wrap="wrap">
              {form.getFieldValue(['resource', 'cpu']) && (
                <Tag>
                  CPU: {form.getFieldValue(['resource', 'cpu'])}{' '}
                  {t('deployment.launcher.Cores')}
                </Tag>
              )}
              {form.getFieldValue(['resource', 'mem']) && (
                <Tag>Memory: {form.getFieldValue(['resource', 'mem'])}</Tag>
              )}
              {form.getFieldValue(['resource', 'accelerator']) > 0 && (
                <Tag>
                  {form.getFieldValue(['resource', 'acceleratorType'])}:{' '}
                  {form.getFieldValue(['resource', 'accelerator'])}{' '}
                  {t('deployment.launcher.Devices')}
                </Tag>
              )}
            </BAIFlex>
          </Descriptions.Item>
        </Descriptions>
      </BAICard>

      {/* Deployment Strategy and Initial Revision Summary */}
      <BAICard
        title={t('deployment.launcher.DeploymentStrategy')}
        showDivider
        size="small"
        status={
          form.getFieldError(['deploymentStrategy', 'type']).length > 0 ||
          form.getFieldError(['initialRevision', 'name']).length > 0 ||
          form.getFieldError(['environments', 'environment']).length > 0 ||
          form.getFieldError(['environments', 'version']).length > 0 ||
          form.getFieldError(['environments', 'manual']).length > 0 ||
          form.getFieldError(['initialRevision', 'image', 'name']).length > 0 ||
          form.getFieldError(['initialRevision', 'image', 'architecture'])
            .length > 0 ||
          form.getFieldError([
            'initialRevision',
            'modelRuntimeConfig',
            'runtimeVariant',
          ]).length > 0
            ? 'error'
            : undefined
        }
        extraButtonTitle={t('button.Edit')}
        onClickExtraButton={() => onClickEditStep('deployment')}
      >
        <Descriptions size="small" column={1}>
          <Descriptions.Item
            label={t('deployment.launcher.DeploymentStrategy')}
          >
            {form.getFieldValue(['deploymentStrategy', 'type']) ===
            'ROLLING' ? (
              t('deployment.launcher.RollingUpdate')
            ) : form.getFieldValue(['deploymentStrategy', 'type']) ===
              'BLUE_GREEN' ? (
              t('deployment.launcher.BlueGreenDeployment')
            ) : form.getFieldValue(['deploymentStrategy', 'type']) ===
              'CANARY' ? (
              t('deployment.launcher.CanaryDeployment')
            ) : (
              <Typography.Text type="secondary">
                {t('general.None')}
              </Typography.Text>
            )}
          </Descriptions.Item>
          <Descriptions.Item label={t('deployment.launcher.RevisionName')}>
            {form.getFieldValue(['initialRevision', 'name']) || (
              <Typography.Text type="secondary">
                {t('general.None')}
              </Typography.Text>
            )}
          </Descriptions.Item>
          <Descriptions.Item label={t('deployment.launcher.ContainerImage')}>
            <BAIFlex direction="column" gap="xxs">
              <Typography.Text>
                {form.getFieldValue(['environments', 'manual']) ||
                  form.getFieldValue(['environments', 'version']) ||
                  form.getFieldValue(['initialRevision', 'image', 'name']) || (
                    <Typography.Text type="secondary">
                      {t('general.None')}
                    </Typography.Text>
                  )}
                {form.getFieldValue([
                  'environments',
                  'image',
                  'architecture',
                ]) &&
                  ` (${form.getFieldValue(['environments', 'image', 'architecture'])})`}
              </Typography.Text>
            </BAIFlex>
          </Descriptions.Item>
          {form.getFieldValue([
            'initialRevision',
            'modelRuntimeConfig',
            'runtimeVariant',
          ]) && (
            <Descriptions.Item label={t('deployment.launcher.RuntimeVariant')}>
              {form.getFieldValue([
                'initialRevision',
                'modelRuntimeConfig',
                'runtimeVariant',
              ])}
            </Descriptions.Item>
          )}
          {form.getFieldValue([
            'initialRevision',
            'modelMountConfig',
            'mountDestination',
          ]) && (
            <Descriptions.Item
              label={t('deployment.launcher.MountDestination')}
            >
              {form.getFieldValue([
                'initialRevision',
                'modelMountConfig',
                'mountDestination',
              ])}
            </Descriptions.Item>
          )}
        </Descriptions>
      </BAICard>
    </BAIFlex>
  );
};

export default DeploymentLauncherPreview;
