#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".ts$")
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
LWHITE="\033[1;37m"
GREEN="\033[0;92m"
RED="\033[0;91m"
YELLOW="\033[0;93m"
NC="\033[0m"
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\n${LWHITE}Validating Javascript:${NC}\n"

# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
  exit 1
fi

for FILE in $STAGED_FILES
do
  "$ESLINT" "$FILE" "-c" "$(git rev-parse --show-toplevel)/.eslintrc.json" "--quiet"

  if [[ "$?" == 0 ]]; then
    printf "\t${YELLOW}ESLint Passed: $FILE${NC}\n"
  else
    printf "\t${RED}ESLint Failed: $FILE${NC}}\n"
    PASS=false
  fi
done

printf "\n${LWHITE}Javascript validation completed.${NC}\n"

if ! $PASS; then
  printf "${RED}[Validation FAILED]${NC} Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  printf "${GREEN}[Validation PASSED]${NC}\n"
fi

exit $?