import searchIndexJson from '../../generated/searchIndex.json';

/**
 * Shape of `react/src/generated/searchIndex.json`, generated by
 * `react/scripts/build-search-index.mjs` (`pnpm run search-index`).
 * Every field holds i18n KEYS, never resolved strings — the palette resolves
 * them through `t()` at query time so all locales come for free.
 */

/** A URL-backed tab strip entry: `?<param>=<key>`. */
export interface SearchIndexTab {
  param: string;
  key: string;
  /** Absent when the tab strip declares no `label: t('…')` sibling. */
  labelKey?: string;
}

/** One `SettingItem` row inside a `SettingList`, addressed by its title key. */
export interface SearchIndexSetting {
  key: string;
  /** `?tab=` key whose branch renders the `SettingList`, when the page is tabbed. */
  tab?: string;
  /** i18n key of the owning `SettingGroup`'s title. */
  groupKey?: string;
  /** The group's `data-testid`. */
  groupId?: string;
  /** The item's own `data-testid`, where one exists. */
  testId?: string;
  /** Body text of this item: every `t()` key in its `description`. */
  descriptionKeys: Array<string>;
}

/** One indexed route: a page hit plus the tabs and setting items it owns. */
export interface SearchIndexEntry {
  menuKey: string | null;
  scope: string | null;
  /** Route path; `:projectName` is filled in at query time. */
  path: string;
  labelKey: string | null;
  /** Repo-relative files the route renders, for debugging the index. */
  component: Array<string>;
  tabs: Array<SearchIndexTab>;
  settings: Array<SearchIndexSetting>;
  /** Body keys: page vocabulary minus titles, tab/setting keys, and chrome. */
  keys: Array<string>;
}

export interface SearchIndex {
  version: number;
  generatedFrom: string;
  entries: Array<SearchIndexEntry>;
}

const searchIndex = searchIndexJson as SearchIndex;

export const getSearchIndex = (): SearchIndex => searchIndex;
