name: Build & Commit static files
on:
  release:
    types: [published]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  build_static:
    runs-on: ubuntu-latest
    environment: app-packaging
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Compile Static Build
        run: make dep && make compile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update to ${{ github.ref_name }}
          committer: LablupBot <devops@lablup.com>
          author: LablupBot <devops@lablup.com>
          branch: feature/${{ github.ref_name }}
          delete-branch: true
          title: "feat update to ${{ github.ref_name }}"
          # reviewers: inureyes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
